### ISSUE TITLE
Missing Request.tags column

### ISSUE THREAD

**Issue by n7k1** [randybondsjr/recordtrac-cakephp#10]
When performing a search on the sample dataset, I get an error:

Database Error
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Request.tags' in 'where clause'

It looks like there's no 'Tags' column being created in the 'record-trac.sql' install file.

**Comment by randybondsjr** [comment]
Fixed with commit https://github.com/randybondsjr/recordtrac-cakephp/commit/eb25a619272058f3cd57a74c53d312c30d103b12
