### ISSUE TITLE
Unknown column 'DocType.name' error when creating new request

### ISSUE THREAD

**Issue by n7k1** [randybondsjr/recordtrac-cakephp#11]
When trying to create a new request, this error occurs:

Database Error
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'DocType.name' in 'field list'

**Comment by n7k1** [comment]
In 

change line 10:
 'prettyDocName' => 'CONCAT(DocType.name, " - ", Department.name)'

to:
 'prettyDocName' => 'CONCAT(Doctype.name, " - ", Department.name)'

that seems to fix it.  This error never showed up on my Windows box.  Only my linux one.

**Comment by randybondsjr** [comment]
Those don't look any different?

**Comment by n7k1** [comment]
DocType changed to Doctype

It only makes a difference on a Linux platform.  My Windows box didn't complain about it

**Comment by randybondsjr** [comment]
Cool, thanks, that makes sense (Windows traditionally is agnostic on case sensitivity(
