### ISSUE TITLE
Unable to login with demo data

### ISSUE THREAD

**Issue by n7k1** [randybondsjr/recordtrac-cakephp#12]
Maybe it's because I'm unfamiliar with cakephp, but I can't login at all.  I'm trying admin@example.com/letmein

I keep getting: 'Invalid username or password, try again'

**Comment by n7k1** [comment]
It looks like the hashed password values aren't valid when you move servers.  So, I modifued the UsersController to allow me to add a user:  $this->Auth->allow('login','logout','view','add');

then I went to /users/add/ to setup a new account.  It worked!

**Comment by randybondsjr** [comment]
Cool, sounds good!
