### ISSUE TITLE
Name field missing in ExtendReason and ClosedReason

### ISSUE THREAD

**Issue by n7k1** [randybondsjr/recordtrac-cakephp#13]
Database Error
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ExtendReason.name' in 'field list'

and in ClosedReason

Database Error
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ClosedReason.name' in 'field list'

**Comment by randybondsjr** [comment]
Fixed with updated .sql import
