### ISSUE TITLE
bcc error when creating a new ticket

### ISSUE THREAD

**Issue by n7k1** [randybondsjr/recordtrac-cakephp#14]
Fatal Error
Error: Call to a member function bcc() on a non-object	
File: /var/www/html/cake/app/Controller/RequestsController.php	
Line: 455

**Comment by randybondsjr** [comment]
Fixed with commit https://github.com/randybondsjr/recordtrac-cakephp/commit/38330ca88fbc61b3258ac0d77ab18aa021f50f16

**Comment by n7k1** [comment]
I've applied the change.  It still won't work...

**Comment by randybondsjr** [comment]
Can you comment out the bcc line and see if that works?

On Wed, Oct 28, 2015 at 10:09 AM, n7k1 notifications@github.com wrote:

> I've applied the change. It still won't work...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/randybondsjr/recordtrac-cakephp/issues/14#issuecomment-151912583
> .

## 

Randy Bonds Jr.

**Comment by n7k1** [comment]
It works if I hard code values in.  It looks like $this->getBccEmail() and $this->getfromEmail are returning null.  I'm new to cake, so I'm trying to figure out how cake knows where to find the config file.

**Comment by randybondsjr** [comment]
Ok! That makes more sense... that error could be a little more specific, but that's on Cake :) You should create a file that mirrors 

> https://github.com/randybondsjr/recordtrac-cakephp/blob/master/app/Config/recordtrac.php 

(changing it to your values) in your Config folder. Then in Config/bootstrap.php add the line

> Configure::load('recordtrac');

**Comment by n7k1** [comment]
Thanks!  I just found it as well.  I was about to update the issue but you beat me to it!  Thanks for all your help!  We're going to test drive this nice piece of software to see if it will fit our needs!
