### ISSUE TITLE
internal_notes table create missing from sql

### ISSUE THREAD

**Issue by n7k1** [randybondsjr/recordtrac-cakephp#9]
Hi,

The internal_notes table is missing from record-trac.sql

I'm guessing this might work, but I think I'm missing a field:

CREATE TABLE `internal_notes` (
  `id` int(11) unsigned NOT NULL,
  `created` datetime DEFAULT NULL,
  `text` text,
  `request_id` int(11) DEFAULT NULL
) 

Can you please provide the sql for the table?

Thanks!

**Comment by randybondsjr** [comment]
Shoot! Yeah, I can get that to you in about 12 hours from now when I'm at a machine I can get to that db.

**Comment by n7k1** [comment]
Thanks!  By the way, nice work.  I'm really keen on getting this working.  I'm not a fan of Python and I can help contribute to this project if I can get it working.  I hope you don't mind me submitting the bugs I find.

**Comment by randybondsjr** [comment]
Not a problem adding bugs, it makes the software better. I've updated the .sql import, so it should be good now.
